---
application:
  name: "linkunshortener"
  project: "linkunshortener"
  organization: "QoveryCommunity"
  port: 3000
routers:
- name: "main-api"
  routes:
  - application_name: "api"
    paths:
    - "/*"
